export const teams = 
    [
        { 
        name: "Andriy",
        surName: "Samaryn",
        position: "Team-lead",
        git: "https://github.com/STIg89",
        linkedin: "https://www.linkedin.com/in/andriy-samarin/",
        description: ["GOD OF PROJECT", "2023"],
        avatar: require('../../../../images/team/Samaryn.jpg'),
        },
        { 
        name: "Halina",
        surName: "Kilbovych",
        position: "Scrum-master",
        git: "https://github.com/HalynaKilbovych",
        linkedin: "https://www.linkedin.com/in/halyna-kilbovych/",
        description: ["Start Page","404","AutoLogin"],
        avatar: require('../../../../images/team/Kilbovych.jpg'),
       },
       { 
        name: "Iryna",
        surName: "Grytsaenko",
        position: "Developer",
        git: "https://github.com/Iryna-Gry",
        linkedin: "https://www.linkedin.com/in/iryna-grytsaenko/",
        description: ["Calendar Page"],
        avatar: require('../../../../images/team/Grytsaenko.jpg'),
       },
       { 
        name: "Victoria",
        surName: "Bilauchuk",
        position: "Developer",
        git: "https://github.com/VictoriaBil",
        linkedin: "https://www.linkedin.com/in/victoria-bilauchuk-187442154",
        description: ["Register Page","Dark Theme"],
        avatar: require('../../../../images/team/Bilauchuk.jpg'),
       },
       { 
        name: "Svitlana",
        surName: "Losieva",
        position: "Developer",
        git: "https://github.com/atevsl",
        linkedin: "https://www.linkedin.com/in/svitlana-losieva/",
        description: ["Calendar Page", "Tasks"],
        avatar: require('../../../../images/team/Losieva.jpg'),
       },
       { 
        name: "Iryna",
        surName: "Zaitseva",
        position: "Developer",
        git: "https://github.com/izaitseva",
        linkedin: "https://www.linkedin.com/in/iryna-zaitseva/",
        description: ["SideBar","Header"],
        avatar: require('../../../../images/team/Zaitseva.jpg'),
       },
       { 
        name: "Kateryna",
        surName: "Vabishchevich",
        position: "Developer",
        git: "https://github.com/Kate-Vabishchevich",
        linkedin: "https://www.linkedin.com/in/kateryna-vabishchevich/",
        description:[ "LoginPage", "Language"],
        avatar: require('../../../../images/team/Vabishchevich.jpg'),
       },
       { 
        name: "Alona",
        surName: "Panchenko",
        position: "Developer",
        git: "https://github.com/Enotishche",
        linkedin: "https://www.linkedin.com/in/alona-panchenko-17477a26b/",
        description: ["Start Page", "Reviews", "Team section"],
        avatar: require('../../../../images/team/Panchenko.jpg'),
       },
       { 
        name: "Oleksandr",
        surName: "Chernomorets",
        position: "Developer",
        git: "https://github.com/AlexanderChernomorets",
        linkedin: "https://www.linkedin.com/",
        description:[ "Review modals"],
        avatar: require('../../../../images/team/Chernomorets.jpg'),
       },
       { 
        name: "Alexey",
        surName: "Alexeev",
        position: "Developer",
        git: "https://github.com/Lelikboss",
        linkedin: "https://www.linkedin.com/in/alexeyalexeevworkpage/",
        description: ["BACK-END", "(registration, tasks, swagger)"],
        avatar: require('../../../../images/team/Alexeev.jpg'),
       },
       { 
        name: "Andrii",
        surName: "Kostenko",
        position: "Developer",
        git: "https://github.com/Andruha0013",
        linkedin: "https://www.linkedin.com/",
        description: ["BACK-END", "(login, reviews, avatar)"],
        avatar: require('../../../../images/team/Kostenko.jpg'),
       },
       { 
        name: "Karyna",
        surName: "Borysenko",
        position: "Developer",
        git: "https://github.com/Karyna-Borysenko",
        linkedin: "https://www.linkedin.com/in/karyna-borysenko/",
        description: ["User Profile"],
        avatar: require('../../../../images/team/Borysenko.jpg'),
       },
       { 
        name: "Viktor",
        surName: "Solomianiy",
        position: "Developer",
        git: "https://github.com/ViktorSolomianiy",
        linkedin: "https://www.linkedin.com/in/viktor-solomianiy/",
        description: ["Calendar Page", "Modal", "Tasks"],
        avatar: require('../../../../images/team/Solomianiy.jpg'),
       },
    ];
 